### ISSUE TITLE
Support Truecrypt

### ISSUE THREAD

**Issue by tomrittervg** [iSECPartners/yontma#22] opened 2013-03-20 11:28 UTC
There's a segment of folks who care about encryption but didn't get a version of Windows w/ Bitlocker (e.g. most consumer store-bought laptops). It would be sweet to either detect Truecrypt and act the same, or enable them to install it in a 'force' mode where it will ignore whether or not the drive has BitLocker.

**Comment by mlynch-isec** [comment] 2013-03-20 15:23
Closing as dupe of issue #5

**Closed as completed by mlynch-isec** 2013-03-20 15:23 UTC
