### ISSUE TITLE
Add Support for accelerometers

### ISSUE THREAD

**Issue by kill-9-me** [iSECPartners/yontma#26] opened 2013-03-26 16:56 UTC
Most modern laptops now have accelerometers built onto the motherboards for various reasons. Monitoring these while the laptop is locked can prevent the laptop from being moved. In high profile situations power and Ethernet can be maintained but the laptop would still need to be moved or turned over to have the hardware directly accessed.

**Comment by andreasjunestam** [comment] 2013-03-26 17:01
Duplicate of issue #4

**Closed as completed by andreasjunestam** 2013-03-26 17:01 UTC
