### ISSUE TITLE
Add Support for USB / Firewire devices

### ISSUE THREAD

**Issue by kill-9-me** [iSECPartners/yontma#25] opened 2013-03-26 16:53 UTC
Checking for new USB / Firewire devices during a locked session could prevent firewire DMA attacks or attacks from USB keychains. 

If a laptop is high profile enough Power or Ethernet can be maintained while transporting.

**Comment by andreasjunestam** [comment] 2013-03-26 17:01
Duplicate of issue #4

**Closed as completed by andreasjunestam** 2013-03-26 17:01 UTC

**Comment by mlynch-isec** [comment] 2013-03-26 17:22
I think this is actually different than #4.

**539F4uL7** - you're saying YoNTMA should hibernate if a USB/Firewire device is _inserted_ while the screen is locked?

**Comment by catskillmarina** [comment] 2013-03-26 17:50
Not exactly. I would like it to hibernate if an UNKNOWN devices is inserted while the screen is locked. Hibernating if any device is inserted while screen is locked would be even better. I would like to see it watching for any suspicious device changes.

**Comment by catskillmarina** [comment] 2013-03-26 17:52
Maybe even blacklist some devices - though this could be easilly subverted, a shutdown if a known mouse wiggler or keylogger was added might give some extra protection. If a known bad device is added i would like to see a hibernate or shutdown whether the screen was locked or not.
